import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

// EXPLICACIÓN: Añadimos '200' al array para que el grosor "ExtraLight" esté disponible.
const hankenGrotesk = Hanken_Grotesk({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="es" className={hankenGrotesk.className}>
        <body>{children}</body>
        </html>
    );
}